"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "motion/react";
import {
  History,
  Search,
  Download,
  Trash2,
  Filter,
  Eye,
  Inbox,
  Sparkles,
  CheckCircle2,
  AlertTriangle,
  X,
  FileText,
  Clock,
} from "lucide-react";
import HelpTooltip from "@/components/common/HelpTooltip";

interface StoredPrediction {
  id: string;
  patientName: string;
  disease: string;
  quantumPrediction: string;
  quantumConfidence: number;
  classicalPrediction: string;
  classicalConfidence: number;
  topDriver: string;
  riskLevel: "High" | "Low";
  timestamp: string;
}

export default function HistoryPage() {
  const [predictions, setPredictions] = useState<StoredPrediction[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [riskFilter, setRiskFilter] = useState<"ALL" | "High" | "Low">("ALL");
  const [selectedCase, setSelectedCase] = useState<StoredPrediction | null>(null);

  const loadHistory = () => {
    if (typeof window !== "undefined") {
      try {
        const stored = localStorage.getItem("quantumx_prediction_history");
        if (stored) {
          const parsed = JSON.parse(stored);
          if (Array.isArray(parsed)) {
            setPredictions(parsed);
          }
        } else {
          setPredictions([]);
        }
      } catch (err) {
        console.error("Failed to load history:", err);
      }
    }
  };

  useEffect(() => {
    loadHistory();
  }, []);

  const handleDeleteRecord = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const updated = predictions.filter((p) => p.id !== id);
    setPredictions(updated);
    if (typeof window !== "undefined") {
      localStorage.setItem("quantumx_prediction_history", JSON.stringify(updated));
    }
    if (selectedCase?.id === id) {
      setSelectedCase(null);
    }
  };

  const handleClearAll = () => {
    if (confirm("Are you sure you want to clear all screening records from this session?")) {
      setPredictions([]);
      if (typeof window !== "undefined") {
        localStorage.removeItem("quantumx_prediction_history");
      }
      setSelectedCase(null);
    }
  };

  const handleExportPDF = (pred: StoredPrediction, e: React.MouseEvent) => {
    e.stopPropagation();
    const summary = `
QUANTUMX MEDICAL SCREENING REPORT
===================================================
Case ID:              ${pred.id}
Patient Name / ID:    ${pred.patientName}
Health Category:      ${pred.disease}
Date & Time:          ${pred.timestamp}

DIAGNOSIS RESULTS:
- Quantum Model:      ${pred.quantumPrediction} (${pred.quantumConfidence}%)
- Standard ML Model:  ${pred.classicalPrediction} (${pred.classicalConfidence}%)
- Risk Level:         ${pred.riskLevel} Risk

KEY DIAGNOSTIC FACTOR:
- Primary Driver:     ${pred.topDriver}

Generated by QuantumX Quantum Diagnostic System.
    `.trim();

    const blob = new Blob([summary], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Medical_Report_${pred.id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const filteredPredictions = predictions.filter((p) => {
    const matchesSearch =
      p.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.patientName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.disease.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.topDriver.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesFilter = riskFilter === "ALL" || p.riskLevel === riskFilter;

    return matchesSearch && matchesFilter;
  });

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.35, ease: "easeOut" }}
      className="space-y-5 pb-12 w-full"
    >
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-hairline pb-4">
        <div>
          <div className="flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-quantum" />
            <span className="text-[11px] font-mono uppercase tracking-wider text-quantum font-semibold">
              Medical Records
            </span>
          </div>
          <h1 className="font-serif text-2xl sm:text-3xl font-light text-ink tracking-tight">
            Patient Screening History
          </h1>
          <p className="text-xs text-ink-soft font-light">
            Review and export past patient screenings run during your active session.
          </p>
        </div>

        {predictions.length > 0 && (
          <button
            type="button"
            onClick={handleClearAll}
            className="px-3 py-1.5 rounded-lg border border-hairline bg-parchment hover:bg-red-50 text-ink-soft hover:text-red-700 text-xs font-medium flex items-center gap-1.5 transition-colors cursor-pointer self-start sm:self-auto"
          >
            <Trash2 size={13} /> Clear All Records
          </button>
        )}
      </div>

      {/* Filter and Search Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        {/* Search */}
        <div className="relative max-w-sm w-full">
          <Search size={14} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-soft" />
          <input
            type="text"
            placeholder="Search by Patient ID, disease, factor..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full h-10 pl-9 pr-3 rounded-xl bg-parchment border border-hairline text-xs text-ink placeholder:text-ink-soft/60 focus:outline-none focus:border-quantum/60 shadow-2xs font-sans"
          />
        </div>

        {/* Risk Filter Buttons */}
        <div className="flex items-center gap-1.5 p-1 bg-cream-deep/60 rounded-xl border border-hairline text-xs font-sans">
          <button
            type="button"
            onClick={() => setRiskFilter("ALL")}
            className={`px-3 py-1.5 rounded-lg transition-all text-xs cursor-pointer ${
              riskFilter === "ALL"
                ? "bg-parchment text-ink shadow-xs border border-hairline font-semibold"
                : "text-ink-soft hover:text-ink"
            }`}
          >
            All Cases ({predictions.length})
          </button>
          <button
            type="button"
            onClick={() => setRiskFilter("High")}
            className={`px-3 py-1.5 rounded-lg transition-all text-xs cursor-pointer ${
              riskFilter === "High"
                ? "bg-red-50 text-red-700 shadow-xs border border-red-200 font-semibold"
                : "text-ink-soft hover:text-ink"
            }`}
          >
            High Risk ({predictions.filter((p) => p.riskLevel === "High").length})
          </button>
          <button
            type="button"
            onClick={() => setRiskFilter("Low")}
            className={`px-3 py-1.5 rounded-lg transition-all text-xs cursor-pointer ${
              riskFilter === "Low"
                ? "bg-emerald-50 text-emerald-700 shadow-xs border border-emerald-200 font-semibold"
                : "text-ink-soft hover:text-ink"
            }`}
          >
            Low Risk ({predictions.filter((p) => p.riskLevel === "Low").length})
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      {predictions.length === 0 ? (
        /* GENUINE REAL EMPTY STATE */
        <div className="p-8 sm:p-12 rounded-2xl bg-parchment border border-hairline shadow-2xs text-center space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-cream-deep/60 border border-hairline text-ink-soft mx-auto flex items-center justify-center">
            <Inbox size={22} className="text-ink-soft" />
          </div>
          <div className="space-y-1 max-w-md mx-auto">
            <h3 className="font-serif text-lg font-medium text-ink">
              No saved patient screenings
            </h3>
            <p className="text-xs text-ink-soft font-light leading-relaxed">
              When you perform diagnostic screenings in the Patient Diagnosis tab, each result and patient report will automatically appear here.
            </p>
          </div>
          <div className="pt-2">
            <Link
              href="/predict"
              className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-ink text-parchment font-medium text-xs tracking-wider hover:opacity-90 transition-all shadow-sm cursor-pointer"
            >
              <Sparkles size={13} className="text-quantum" /> Start New Patient Screening
            </Link>
          </div>
        </div>
      ) : filteredPredictions.length === 0 ? (
        <div className="p-8 rounded-2xl bg-parchment border border-hairline text-center space-y-2">
          <p className="text-xs text-ink-soft">No screening cases match your search query or filter.</p>
          <button
            type="button"
            onClick={() => {
              setSearchQuery("");
              setRiskFilter("ALL");
            }}
            className="text-xs font-semibold text-quantum hover:underline cursor-pointer"
          >
            Reset search filters
          </button>
        </div>
      ) : (
        /* Populated Table */
        <div className="bg-parchment rounded-2xl border border-hairline shadow-xs overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs font-sans">
              <thead className="bg-cream-deep/40 border-b border-hairline text-[11px] font-mono uppercase tracking-wider text-ink-soft">
                <tr>
                  <th className="py-3.5 px-4 font-semibold">Case ID</th>
                  <th className="py-3.5 px-4 font-semibold">Patient Name</th>
                  <th className="py-3.5 px-4 font-semibold">Test Category</th>
                  <th className="py-3.5 px-4 font-semibold">Quantum Result</th>
                  <th className="py-3.5 px-4 font-semibold">Standard Model</th>
                  <th className="py-3.5 px-4 font-semibold">Primary Factor</th>
                  <th className="py-3.5 px-4 font-semibold">Timestamp</th>
                  <th className="py-3.5 px-4 font-semibold text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-hairline text-ink">
                {filteredPredictions.map((pred) => (
                  <tr
                    key={pred.id}
                    onClick={() => setSelectedCase(pred)}
                    className="hover:bg-cream/60 transition-colors cursor-pointer"
                  >
                    <td className="py-3.5 px-4 font-mono text-xs font-semibold text-quantum">
                      {pred.id}
                    </td>
                    <td className="py-3.5 px-4 font-medium text-xs text-ink">{pred.patientName}</td>
                    <td className="py-3.5 px-4 text-ink-soft text-xs">{pred.disease}</td>
                    <td className="py-3.5 px-4 font-mono font-medium">
                      <span
                        className={`inline-block px-2.5 py-1 rounded-full text-[10px] ${
                          pred.riskLevel === "High"
                            ? "bg-red-50 text-red-700 border border-red-200"
                            : "bg-emerald-50 text-emerald-700 border border-emerald-200"
                        }`}
                      >
                        {pred.quantumPrediction} ({pred.quantumConfidence}%)
                      </span>
                    </td>
                    <td className="py-3.5 px-4 font-mono text-ink-soft text-xs">
                      {pred.classicalPrediction} ({pred.classicalConfidence}%)
                    </td>
                    <td className="py-3.5 px-4 text-xs font-mono text-ink truncate max-w-[180px]" title={pred.topDriver}>
                      {pred.topDriver}
                    </td>
                    <td className="py-3.5 px-4 text-xs text-ink-soft font-mono">{pred.timestamp}</td>
                    <td className="py-3.5 px-4 text-right space-x-2">
                      <button
                        type="button"
                        onClick={(e) => handleExportPDF(pred, e)}
                        className="p-1.5 rounded-lg hover:bg-cream border border-transparent hover:border-hairline text-ink-soft hover:text-ink transition-colors cursor-pointer"
                        title="Download Summary Report"
                      >
                        <Download size={14} />
                      </button>
                      <button
                        type="button"
                        onClick={(e) => handleDeleteRecord(pred.id, e)}
                        className="p-1.5 rounded-lg hover:bg-red-50 border border-transparent hover:border-red-200 text-ink-soft hover:text-red-700 transition-colors cursor-pointer"
                        title="Delete Record"
                      >
                        <Trash2 size={14} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Case Details Modal */}
      <AnimatePresence>
        {selectedCase && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setSelectedCase(null)}
              className="fixed inset-0 bg-ink/30 backdrop-blur-xs z-50"
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 15 }}
              className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-lg bg-parchment rounded-2xl border border-hairline shadow-2xl z-50 p-5 space-y-4 max-h-[90vh] overflow-y-auto"
            >
              <div className="flex items-center justify-between border-b border-hairline pb-3">
                <div>
                  <span className="text-[10px] font-mono uppercase tracking-wider text-quantum font-semibold">
                    Case Summary
                  </span>
                  <h3 className="font-serif text-lg font-medium text-ink">Case ID: {selectedCase.id}</h3>
                </div>
                <button
                  type="button"
                  onClick={() => setSelectedCase(null)}
                  className="w-7 h-7 rounded-full bg-cream-deep/60 border border-hairline flex items-center justify-center text-ink-soft hover:text-ink cursor-pointer"
                >
                  <X size={14} />
                </button>
              </div>

              <div className="space-y-3 text-xs">
                <div className="grid grid-cols-2 gap-2 p-3 rounded-xl bg-cream/50 border border-hairline">
                  <div>
                    <span className="text-[10px] text-ink-soft">Patient Name / ID</span>
                    <p className="font-medium text-ink">{selectedCase.patientName}</p>
                  </div>
                  <div>
                    <span className="text-[10px] text-ink-soft">Test Category</span>
                    <p className="font-medium text-ink">{selectedCase.disease}</p>
                  </div>
                  <div>
                    <span className="text-[10px] text-ink-soft">Screening Time</span>
                    <p className="font-medium text-ink font-mono">{selectedCase.timestamp}</p>
                  </div>
                  <div>
                    <span className="text-[10px] text-ink-soft">Risk Classification</span>
                    <p className={`font-semibold ${selectedCase.riskLevel === "High" ? "text-red-700" : "text-emerald-700"}`}>
                      {selectedCase.riskLevel} Risk
                    </p>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div className="p-3 rounded-xl bg-cream border border-quantum/30 space-y-1">
                    <span className="text-[9px] font-mono text-quantum font-semibold">Quantum Result</span>
                    <div className="font-serif text-base font-medium text-ink">{selectedCase.quantumPrediction}</div>
                    <div className="text-[10px] font-mono text-quantum font-medium">Confidence: {selectedCase.quantumConfidence}%</div>
                  </div>
                  <div className="p-3 rounded-xl bg-cream border border-hairline space-y-1">
                    <span className="text-[9px] font-mono text-ink-soft font-semibold">Standard Model</span>
                    <div className="font-serif text-base font-medium text-ink">{selectedCase.classicalPrediction}</div>
                    <div className="text-[10px] font-mono text-ink-soft font-medium">Confidence: {selectedCase.classicalConfidence}%</div>
                  </div>
                </div>

                <div className="p-3 rounded-xl bg-cream-deep/30 border border-hairline space-y-1">
                  <span className="text-[9px] font-mono text-ink-soft uppercase tracking-wider font-semibold">
                    Primary Diagnostic Factor
                  </span>
                  <p className="font-mono text-xs font-semibold text-quantum">{selectedCase.topDriver}</p>
                </div>
              </div>

              <div className="pt-2 border-t border-hairline flex items-center justify-between">
                <button
                  type="button"
                  onClick={(e) => handleExportPDF(selectedCase, e)}
                  className="px-3.5 py-1.5 rounded-lg bg-ink text-parchment text-xs font-medium flex items-center gap-1.5 hover:opacity-90 transition-opacity cursor-pointer"
                >
                  <Download size={13} /> Download Report
                </button>
                <button
                  type="button"
                  onClick={() => setSelectedCase(null)}
                  className="px-3.5 py-1.5 rounded-lg bg-cream-deep/60 hover:bg-cream border border-hairline text-ink text-xs font-medium cursor-pointer"
                >
                  Close
                </button>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
